FROM eclipse-temurin:24-jre-alpine
WORKDIR /app

COPY marketplace.jar ./app.jar
COPY marketplace-docker.properties ./marketplace.properties

RUN mkdir -p /app/logs

CMD ["sh", "-c", "java -jar app.jar ${INSTANCE_ID} ${CONFIG_FILE} 2>&1 | tee -a ./logs/${INSTANCE_ID}.log"]
